// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrpIxZJMYJ7itftl_B9p2qyaNemVEsd4Q',
    appId: '1:316219829725:web:82e4397fe1ceb73b15da34',
    messagingSenderId: '316219829725',
    projectId: 'fir-realtime-2c115',
    authDomain: 'fir-realtime-2c115.firebaseapp.com',
    databaseURL: 'https://fir-realtime-2c115-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtime-2c115.firebasestorage.app',
    measurementId: 'G-9P7BJHF1DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABGvSmXiN8ssoq3qnWNUCZ3oqVjHZdHOs',
    appId: '1:316219829725:android:53d351acf50d263315da34',
    messagingSenderId: '316219829725',
    projectId: 'fir-realtime-2c115',
    databaseURL: 'https://fir-realtime-2c115-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtime-2c115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM3Myvo740GuaY8ROVgzKrStYT458PyVQ',
    appId: '1:316219829725:ios:cb62d28c58ae859d15da34',
    messagingSenderId: '316219829725',
    projectId: 'fir-realtime-2c115',
    databaseURL: 'https://fir-realtime-2c115-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtime-2c115.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseRealtimeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM3Myvo740GuaY8ROVgzKrStYT458PyVQ',
    appId: '1:316219829725:ios:cb62d28c58ae859d15da34',
    messagingSenderId: '316219829725',
    projectId: 'fir-realtime-2c115',
    databaseURL: 'https://fir-realtime-2c115-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtime-2c115.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseRealtimeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrpIxZJMYJ7itftl_B9p2qyaNemVEsd4Q',
    appId: '1:316219829725:web:b6182d50228eda5d15da34',
    messagingSenderId: '316219829725',
    projectId: 'fir-realtime-2c115',
    authDomain: 'fir-realtime-2c115.firebaseapp.com',
    databaseURL: 'https://fir-realtime-2c115-default-rtdb.firebaseio.com',
    storageBucket: 'fir-realtime-2c115.firebasestorage.app',
    measurementId: 'G-K8ZTHYML8L',
  );

}